#!/usr/bin/env python3
"""Compare the matched five-seed codec-TTS before/after summaries."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np


def paired_ci(values: list[float], n: int = 10_000) -> list[float]:
    array = np.asarray(values, dtype=float)
    rng = np.random.default_rng(20260731)
    means = np.asarray([rng.choice(array, len(array), replace=True).mean() for _ in range(n)])
    return np.quantile(means, [0.025, 0.975]).tolist()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--before", default="experiments/results/codec_tts_unique_before/summary.json")
    parser.add_argument("--after", default="experiments/results/codec_tts_corrective/summary.json")
    parser.add_argument("--output", default="experiments/results/codec_tts_corrective/comparison.json")
    parser.add_argument("--markdown-output", default="experiments/results/codec_tts_corrective/comparison.md")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    before = json.loads((root / args.before).read_text())
    after = json.loads((root / args.after).read_text())
    if before["seeds"] != after["seeds"]:
        raise RuntimeError("Before/after seeds are not paired")
    report = {"schema_version": 1, "n_trials": len(before["seeds"]), "seeds": before["seeds"], "metrics": {}, "diagnostics": {}}
    for split in ("overall", "domain_terms", "common_terms"):
        left = before["metrics"][split]["codec_tts_trial_values"]
        right = after["metrics"][split]["codec_tts_trial_values"]
        delta = [b - a for a, b in zip(left, right)]
        report["metrics"][split] = {
            "before_mean_wer": float(np.mean(left)), "after_mean_wer": float(np.mean(right)),
            "paired_after_minus_before_trial_values": delta,
            "paired_mean_delta": float(np.mean(delta)), "paired_trial_bootstrap_95_ci": paired_ci(delta),
        }
    for name in ("absolute_sequence_length_error_tokens", "eos_rate", "generation_failure_rate", "si_sdr_db_conditional_on_decodable_output"):
        left = before["diagnostics"][name]["trial_values"]
        right = after["diagnostics"][name]["trial_values"]
        delta = [b - a for a, b in zip(left, right)]
        report["diagnostics"][name] = {"before_mean": float(np.mean(left)), "after_mean": float(np.mean(right)), "paired_mean_delta": float(np.mean(delta)), "paired_trial_bootstrap_95_ci": paired_ci(delta)}
    output = root / args.output
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(report, indent=2), encoding="utf-8")
    lines = ["# Codec-TTS corrective comparison", "", "| Metric | Before | After | Paired after−before (95% trial CI) | N_trials |", "|---|---:|---:|---:|---:|"]
    for split, label in (("overall", "Overall WER"), ("domain_terms", "Domain WER"), ("common_terms", "Common WER")):
        row = report["metrics"][split]; ci = row["paired_trial_bootstrap_95_ci"]
        lines.append(f"| {label} | {row['before_mean_wer']*100:.2f}% | {row['after_mean_wer']*100:.2f}% | {row['paired_mean_delta']*100:+.2f} pp ({ci[0]*100:+.2f}–{ci[1]*100:+.2f}) | 5 |")
    row = report["diagnostics"]["absolute_sequence_length_error_tokens"]; ci = row["paired_trial_bootstrap_95_ci"]
    lines.append(f"| Mean absolute length error | {row['before_mean']:.2f} tokens | {row['after_mean']:.2f} tokens | {row['paired_mean_delta']:+.2f} ({ci[0]:+.2f}–{ci[1]:+.2f}) | 5 |")
    lines += ["", "Duration control reduced length error but did not improve held-out round-trip WER. The repetition penalty was disabled after its preregistered tiny-set diagnostic worsened free-running error.", "", "Generated by `scripts/summarize_codec_tts_correction.py`.", ""]
    markdown = root / args.markdown_output
    markdown.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
