#!/usr/bin/env python3
"""Generate a matched-seed before/after summary for the codec collapse correction."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np


def ci(values: list[float], n: int = 10_000) -> list[float]:
    array = np.asarray(values, dtype=float)
    rng = np.random.default_rng(20260731)
    means = np.asarray([rng.choice(array, len(array), replace=True).mean() for _ in range(n)])
    return np.quantile(means, [0.025, 0.975]).tolist()


def keyed(payload: dict) -> dict:
    return {(cell["quantizer"], cell["nominal_bitrate_bps"]): cell for cell in payload["cells"]}


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--before-dir", default="experiments/results/codec_medical")
    parser.add_argument("--after-dir", default="experiments/results/codec_medical_corrective")
    parser.add_argument("--output", default="experiments/results/codec_medical_corrective/comparison.json")
    parser.add_argument("--markdown-output", default="experiments/results/codec_medical_corrective/comparison.md")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    before_signal = keyed(json.loads((root / args.before_dir / "signal_summary.json").read_text()))
    after_signal = keyed(json.loads((root / args.after_dir / "signal_summary.json").read_text()))
    before_wer = keyed(json.loads((root / args.before_dir / "wer_summary.json").read_text()))
    after_wer = keyed(json.loads((root / args.after_dir / "wer_summary.json").read_text()))
    rows = []
    for key in sorted(before_signal, key=lambda x: (x[1], x[0])):
        bs, a_s, bw, aw = before_signal[key], after_signal[key], before_wer[key], after_wer[key]
        signal_delta = [after - before for before, after in zip(bs["si_sdr_db"]["trial_values"], a_s["si_sdr_db"]["trial_values"])]
        bitrate_delta = [after - before for before, after in zip(bs["empirical_bitrate_bps"]["trial_values"], a_s["empirical_bitrate_bps"]["trial_values"])]
        before_w = bw["delta_wer"]["overall"]["adapted_whisper"]["trial_values"]
        after_w = aw["delta_wer"]["overall"]["adapted_whisper"]["trial_values"]
        wer_delta = [after - before for before, after in zip(before_w, after_w)]
        rows.append({"quantizer": key[0], "nominal_bitrate_bps": key[1], "n_trials": 5,
                     "before_empirical_bitrate_bps": bs["empirical_bitrate_bps"]["mean"], "after_empirical_bitrate_bps": a_s["empirical_bitrate_bps"]["mean"], "paired_bitrate_delta_ci": ci(bitrate_delta),
                     "before_si_sdr_db": bs["si_sdr_db"]["mean"], "after_si_sdr_db": a_s["si_sdr_db"]["mean"], "paired_si_sdr_delta": float(np.mean(signal_delta)), "paired_si_sdr_delta_ci": ci(signal_delta),
                     "before_adapted_delta_wer": bw["delta_wer"]["overall"]["adapted_whisper"]["mean_delta_wer"], "after_adapted_delta_wer": aw["delta_wer"]["overall"]["adapted_whisper"]["mean_delta_wer"], "paired_adapted_delta_wer_change": float(np.mean(wer_delta)), "paired_adapted_delta_wer_change_ci": ci(wer_delta)})
    report = {"schema_version": 1, "n_trials_per_cell": 5, "delta_definition": "after minus before", "cells": rows}
    output = root / args.output; output.write_text(json.dumps(report, indent=2), encoding="utf-8")
    lines = ["# Codec-collapse corrective comparison", "", "| Codec | Nominal | Empirical bitrate before→after | SI-SDR before→after | Adapted ΔWER before→after | Paired WER change (95% trial CI) | N_trials |", "|---|---:|---:|---:|---:|---:|---:|"]
    for row in rows:
        wci = row["paired_adapted_delta_wer_change_ci"]
        lines.append(f"| {row['quantizer'].upper()} | {row['nominal_bitrate_bps']} bps | {row['before_empirical_bitrate_bps']:.2f}→{row['after_empirical_bitrate_bps']:.2f} bps | {row['before_si_sdr_db']:.2f}→{row['after_si_sdr_db']:.2f} dB | {row['before_adapted_delta_wer']*100:+.2f}→{row['after_adapted_delta_wer']*100:+.2f} pp | {row['paired_adapted_delta_wer_change']*100:+.2f} pp ({wci[0]*100:+.2f}–{wci[1]*100:+.2f}) | 5 |")
    lines += ["", "EMA/dead-code handling and FSQ normalization restored utilization and SI-SDR, but downstream WER improved in four of six cells and regressed at VQ 400/500. Realized bitrates are not matched before/after, so this is a corrective ablation rather than a controlled codec ranking.", "", "Generated by `scripts/summarize_codec_corrective_comparison.py`.", ""]
    (root / args.markdown_output).write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
